---
title: "CV"
output:
  html_document:
    toc: true
    toc_depth: 2
    theme: flatly
    df_print: paged
---

# Adam Bartosik

**Poznań / Kalisz**\
📧 [97703\@student.up.poznan.pl](mailto:97703@student.up.poznan.pl){.email}\
🔗 Portfolio: [link do dysku](https://drive.google.com/drive/folders/1NgG5ogcll6bGOK894mdMc6FjC0vjdXZK?usp=drive_link)

------------------------------------------------------------------------

## 👤 O mnie

Jestem osobą zainteresowaną programowaniem oraz produkcją i realizacją nagrań dźwiękowych. Łączę umiejętności techniczne z doświadczeniem dydaktycznym, co pozwala mi skutecznie przekazywać wiedzę i pracować zespołowo. Aktualnie rozwijam się w kierunku IT oraz technologii audio.

------------------------------------------------------------------------

## 🎓 Wykształcenie

**I Liceum Ogólnokształcące im. Adama Asnyka w Kaliszu**\
*Wykształcenie średnie*\
2019 – 2023

**Szkoła Muzyki Nowoczesnej we Wrocławiu**\
*Kierunek: Technik realizacji nagrań*\
2024 – 2026\
- w trakcie kształcenia\
- oczekiwanie na wyniki egzaminów zawodowych

**Uniwersytet Przyrodniczy w Poznaniu**\
*Kierunek: Informatyka i Inżynieria Danych*\
2023 – obecnie\
- w trakcie kształcenia\

------------------------------------------------------------------------

## 🛠 Umiejętności

### Techniczne

-   Programowanie (Python, C++, C#)
-   Obsługa pakietu Microsoft Office
-   Produkcja i realizacja nagrań dźwiękowych

### Narzędzia i programy

-   Ableton Live
-   Microsoft Office
-   Visual Studio

### Języki obce

-   Angielski – komunikatywny

### Umiejętności miękkie

-   Praca zespołowa\
-   Umiejętności dydaktyczne\
-   Komunikatywność\
-   Samodzielność i dobra organizacja pracy

------------------------------------------------------------------------

## 💼 Doświadczenie

**Code Now / IT Korepetycje**\
*Korepetytor informatyki*\
2023 – obecnie\
- przekazywanie wiedzy z zakresu programowania\
- nauczanie obsługi pakietu Microsoft Office\
- wprowadzanie do podstaw SQL\
- przygotowanie uczniów do egzaminu maturalnego\
- dostosowywanie metod nauczania do indywidualnych potrzeb ucznia

------------------------------------------------------------------------
